### ISSUE TITLE
Issue in "training_corpus_pos_final.txt"

### ISSUE THREAD

**Issue by KhondokerIslam** [Ayubur/bangla-sentiment-analysis#1]
Your sentences in "training_corpus_pos_final.txt" is full of '?' signs for bengali character. Hoping for a quick fix in order to help us at max. 

Cheers,

**Comment by shafayet98** [comment]
"training_corpus_pos_final.txt" has an issue, all the texts shows as "??" please fix this if you can 
thanks.
